version: '3.7'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project/:/usr/project/main/
    ports:
      - 8002:8000
 
 
  db:
    image: mongodb
    env_file:
      - .env
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: project-crud-fastapi
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

 


